export const regions: Record<string, string> = {
  sfo1: "San Francisco",
  iad1: "Washington, D.C.",
  pdx1: "Portland",
  cle1: "Cleveland",
  gru1: "São Paulo",
  hkg1: "Hong Kong",
  hnd1: "Tokyo",
  icn1: "Seoul",
  kix1: "Osaka",
  sin1: "Singapore",
  bom1: "Mumbai",
  syd1: "Sydney",
  cdg1: "Paris",
  arn1: "Stockholm",
  dub1: "Dublin",
  lhr1: "London",
  fra1: "Frankfurt",
  cpt1: "Cape Town",
  dev1: "localhost",
};
